### ISSUE TITLE
[Question] Other MC versions?

### ISSUE THREAD

**Issue by supersaiyansubtlety** [JacktheDevel0per/FilledTotheBrim#1]
Do you plan to support other versions of Minecraft, especially newer versions?

**Comment by JacktheDevel0per** [comment]
Sure, I can update it, also if requested can downgrade it, it's pretty simple os it can support many versions (that fabric supports in general) and even can be made into a class patch for even older versions of mc.

**Comment by JacktheDevel0per** [comment]
Done.
