### ISSUE TITLE
[Suggestion] Add option to allow filled shulkerboxes

### ISSUE THREAD

**Issue by energy11a** [JacktheDevel0per/FilledTotheBrim#4]
Add option to allow shulkerboxes with items inside to be placed into shulkerboxes.
If not possible/not planned in this mod please give pointers, where I could learn to make necessary changes.

**Comment by JacktheDevel0per** [comment]
Well this mod was not really meant for that but all you need to do is change the checks in the mixins to true, it can technically be added but then I would need to write a config save system but I could do that pretty easy now that I think about it

**Comment by energy11a** [comment]
Thanks. Got it to work.
