### ISSUE TITLE
missing 1.1.0 in modrinth

### ISSUE THREAD

**Issue by yesn0t** [JacktheDevel0per/FilledTotheBrim#5]
hello, i use this mod on my 1.17.1 instance and until today i didn't know it was updated to 1.18+ ,

now that i found 1.1.0 in github releases i don't mind but i do wonder,
is there any problem preventing the current version from making it to modrinth ?

thanks x)

**Comment by JacktheDevel0per** [comment]
Oh hmm I can add it I guess

**Comment by JacktheDevel0per** [comment]
Added to Modrinth

**Comment by JacktheDevel0per** [comment]
Also I am Sorry bout that.

**Comment by yesn0t** [comment]
thanks again and no worries ^^
